export const id200 = "Thunderstorm with Light Rain"
export const id201 = "Thunderstorm with Rain"
export const id202 = "Thunderstorm with Heavy Rain"
export const id210 = "Light Thunderstorm"
export const id211 = "Thunderstorm"
export const id212 = "Heavy Thunderstorm"
export const id221 = "Ragged Thunderstorm"
export const id230 = "Thunderstorm with Light Drizzle"
export const id231 = "Thunderstorm with Drizzle"
export const id232 = "Thunderstorm with Heavy Drizzle"

export const id300 = "Light Drizzle"
export const id301 = "Drizzle"
export const id302 = "Heavy Drizzle"
export const id310 = "Light Drizzle"
export const id311 = "Drizzle"
export const id312 = "Heavy Drizzle"
export const id313 = "Shower Rain"
export const id314 = "Heavy Shower Rain"
export const id321 = "Shower Drizzle"

export const id500 = "Light Rain"
export const id501 = "Rain"
export const id502 = "Heavy Rain"
export const id503 = "Very Heavy Rain"
export const id504 = "Extreme Rain"
export const id511 = "Freezing Rain"
export const id520 = "Light Rain"
export const id521 = "Rain"
export const id522 = "Heavy Rain"
export const id531 = "Rain"

export const id600 = "Light Snow"
export const id601 = "Snow"
export const id602 = "Heavy Snow"
export const id611 = "Sleet"
export const id612 = "Heavy Sleet"
export const id615 = "Light Rain and Snow"
export const id616 = "Rain and Snow"
export const id620 = "Light Snow"
export const id621 = "Snow"
export const id622 = "Heavy Snow"

export const id701 = "Mist"
export const id711 = "Smoke"
export const id721 = "Haze"
export const id731 = "Sand"
export const id741 = "Fog"
export const id751 = "Sand"
export const id761 = "Dust"
export const id762 = "Volcanic Ash"
export const id771 = "Squalls"
export const id781 = "Tornado"

export const id800 = "Clear Sky"

export const id801 = "Few Clouds"
export const id802 = "Scattered Clouds"
export const id803 = "Broken Clouds"
export const id804 = "Overcast"